name: Release

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish:
    name: Build ${{ matrix.target }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          # - os: macos-latest
          #   target: aarch64-apple-darwin
          # - os: macos-latest
          #   target: x86_64-apple-darwin
          - os: windows-latest
            target: x86_64-pc-windows-msvc

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Rust Toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Install Additional Tools
        run: cargo install cargo-bundle
