name: Release

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish:
    name: Build - ${{ matrix.target }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          # - os: macos-latest
          #   target: aarch64-apple-darwin
          # - os: macos-latest
          #   target: x86_64-apple-darwin
          - os: windows-latest
            target: x86_64-pc-windows-msvc

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Rust Toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Install Additional Tools
        run: cargo install cargo-bundle

      - name: Build
        run: cargo bundle --release --target ${{ matrix.target }}

      - name: Package
        run: |
          cd target/${{ matrix.target }}/release/bundle
          mkdir -p dist
          if [ "${{ matrix.os }}" == "windows-latest" ]; then
            mv msi/*.msi dist
          elif [ "${{ matrix.os }}" == "macos-latest" ]; then
            mv osx/*.app dist
          elif [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
            mv -t deb/*.deb rpm/*.rpm dist
          fi

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: target/${{ matrix.target }}/release/bundle/dist/*
