name: Release

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish:
    name: Build - ${{ matrix.target }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
            target: aarch64-apple-darwin
          # - os: macos-latest
          #   target: x86_64-apple-darwin
          # - os: windows-latest
          #  target: x86_64-pc-windows-msvc

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Rust Toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Install Additional Tools
        run: cargo install cargo-bundle

      - name: Build and Package
        run: cargo xtask bundle --release --target ${{ matrix.target }}

      - name: Move Artifacts
        run: |
          cd target/${{ matrix.target }}/release/bundle

          mkdir -p dist
          if [ "${{ matrix.os }}" == "macos-latest" ]; then
            mv dmg/*.dmg dist
          elif [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
            mv -t deb/*.deb rpm/*.rpm dist
          elif [ "${{ matrix.os }}" == "windows-latest" ]; then
            mv msi/*.msi dist
          fi

      - name: Upload Release Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: release
          path: target/${{ matrix.target }}/release/bundle/dist

      # - name: Release
      #   uses: softprops/action-gh-release@v2
      #   with:
      #     files: target/${{ matrix.target }}/release/bundle/dist/*
