name: Release

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: write

defaults:
  run:
    shell: bash

jobs:
  publish:
    name: Release - ${{ matrix.target }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
            target: aarch64-apple-darwin
          - os: macos-latest
            target: x86_64-apple-darwin
          - os: windows-latest
            target: x86_64-pc-windows-msvc
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Rust Toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          target: ${{ matrix.target }}

      - name: Build and Package
        run: cargo xtask bundle --release --target ${{ matrix.target }}

      - name: Move Artifacts
        run: |
          cd target/${{ matrix.target }}/release/bundle

          mkdir -p dist
          if [ "${{ matrix.os }}" == "macos-latest" ]; then
            mv dmg/*.dmg dist
          elif [ "${{ matrix.os }}" == "windows-latest" ]; then
            mv msi/*.msi dist
          elif [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
            mv -t dist deb/*.deb rpm/*.rpm
          fi

      - name: Upload Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: target/${{ matrix.target }}/release/bundle/dist/*
